rootProject.name = "Blockchain"
include(":app")
include(":data")
include(":domain")
include(":remote")
include(":platform:core-android-deps")
include(":platform:core-kotlin-deps")
include(":platform:core-network-deps")
include(":platform:core-test-deps")
include(":platform:core-integration-test-deps")
