name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    name: "Static analysis step"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run detekt & detekt ktlint wrapper
        run: ./gradlew detekt

  unit_testing:
    name: "Tests step"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run unit tests
        run: ./gradlew clean test

  instrumented_testing:
    name: instrumented testing
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: instrumented testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          arch: x86
          script:
            ./gradlew clean connectedCheck
